spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgresuser
    password: password123
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    show-sql: true